name: api_model_sample
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.9.0
  amplify_auth_cognito: ">=1.4.0 <1.5.0"
  amplify_authenticator: ^1.0.0
  amplify_api: ">=1.4.0 <1.5.0"
  amplify_flutter: ">=1.4.0 <1.5.0"
  amplify_logging_cloudwatch: 0.1.0
  aws_logging_cloudwatch: 0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  amplify_lints: ^2.0.0

flutter:
  uses-material-design: true
